"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { apiRequest } from "../../lib/api";

export default function OnboardingPage() {
  const router = useRouter(); const [subjects, setSubjects] = useState<{ id: string; title: string }[]>([]); const [subjectConfidence, setSubjectConfidence] = useState<Record<string, number>>({}); const [error, setError] = useState("");
  useEffect(() => { apiRequest<{ id: string }[]>("/curriculum/versions").then((versions) => apiRequest<{ id: string; title: string }[]>(`/curriculum/subjects?curriculum_version_id=${versions[0]?.id}`)).then((loadedSubjects) => { setSubjects(loadedSubjects); setSubjectConfidence(Object.fromEntries(loadedSubjects.map((subject) => [subject.id, 3]))); }).catch(() => setSubjects([])); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiRequest("/onboarding", { method: "PUT", body: JSON.stringify({ display_name: form.get("name"), target_exam: "GATE CSE", target_year: Number(form.get("year")), target_rank: Number(form.get("rank")) || null, daily_study_minutes: Number(form.get("minutes")), programming_experience: form.get("experience"), preferred_learning_style: form.get("style") || null, subject_confidence: subjectConfidence }) }); router.push("/diagnostic"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save onboarding"); } }
  return <main className="form-page"><p className="eyebrow">Step 1 of 2</p><h1>Tell us how you&apos;re preparing.</h1><form onSubmit={submit}><input name="name" placeholder="Your name" required /><input name="year" type="number" defaultValue="2027" min="2026" required /><input name="rank" type="number" placeholder="Target rank (optional)" /><input name="minutes" type="number" defaultValue="120" min="15" required /><select name="experience" defaultValue="beginner"><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select><select name="style"><option value="">No preference</option><option value="visual">Visual examples</option><option value="practice">Practice first</option><option value="conceptual">Concept first</option></select>{subjects.length > 0 && <fieldset className="confidence-fields"><legend>How confident are you in each subject?</legend>{subjects.map((subject) => <label key={subject.id}>{subject.title}<select value={subjectConfidence[subject.id] ?? 3} onChange={(event) => setSubjectConfidence({ ...subjectConfidence, [subject.id]: Number(event.target.value) })}><option value={1}>Need to start</option><option value={2}>Low confidence</option><option value={3}>Some confidence</option><option value={4}>Confident</option><option value={5}>Very confident</option></select></label>)}</fieldset>}<button>Continue to diagnostic</button>{error && <p className="error">{error}</p>}</form></main>;
}
